apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - ../../service-account
  - restart-deployment-job.yaml

patches:
  - target:
      kind: ServiceAccount
      name: base-name
    path: patch-service-account.json
    
