apiVersion: apps/v1
kind: Deployment

metadata:
  name: base-name
  namespace: base-namespace

spec:
  replicas: 1

  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"

  selector:
    matchLabels:
      app: base-app

  template:
    metadata:
      labels:
        app: base-app
    spec:
      containers:
        - name: base-image
          image: base-image:base-version

          ports:
            - name: http
              containerPort: 8080

          envFrom:
            - secretRef:
                name: base-secret-env
                optional: true

            - configMapRef:
                name: base-configmap-env
                optional: true

          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 3
  
          startupProbe:
            httpGet:
              path: /startup
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 3

          resources:
            limits:
              cpu: "150"
              memory: "200Mi"
            requests:
              cpu: "150"
              memory: "100Mi"

          #imagePullPolicy: 'Always'

          #securityContext:
          #  runAsNonRoot: true
          #  readOnlyRootFilesystem: true
          #  privileged: false
          #  allowPrivilegeEscalation: false